version: '3.7'

services:
  teamspeak:
    image: teamspeak
    restart: always
    depends_on:
      - database
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: database
      TS3SERVER_DB_USER: ${MYSQL_USER}
      TS3SERVER_DB_PASSWORD: ${MYSQL_PASSWORD}
      TS3SERVER_DB_NAME: ${MYSQL_DATABASE}
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
      TS3SERVER_LICENSEPATH: ${TS3SERVER_LICENSEPATH:-}
    volumes:
      - ./data/ts3server:/var/ts3server

  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
